# Generated by Django 2.2.1 on 2019-05-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='created_at',
        ),
    ]
