# Generated by Django 2.2.1 on 2019-05-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20190530_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
